export type SceneryRole =
  | "pine_tree"
  | "canopy_tree"
  | "bush"
  | "grass"
  | "rock";

export type SceneryCollisionHint = "trunk_canopy" | "sphere" | "none";

export interface SceneryAssetDefinition {
  id: string;
  url: string;
  role: SceneryRole;
  weight: number;
  scaleMin: number;
  scaleMax: number;
  collisionHint: SceneryCollisionHint;
  collisionHeight: number;
  collisionRadius: number;
}

const SCENERY_ASSET_LIBRARY: SceneryAssetDefinition[] = [
  {
    id: "simple-tree-1",
    url: "/scenery-assets/simplenature/Tree1.glb",
    role: "canopy_tree",
    weight: 20,
    scaleMin: 4.5,
    scaleMax: 7.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-2",
    url: "/scenery-assets/simplenature/Tree2.glb",
    role: "canopy_tree",
    weight: 18,
    scaleMin: 4.5,
    scaleMax: 7.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-3",
    url: "/scenery-assets/simplenature/Tree3.glb",
    role: "pine_tree",
    weight: 18,
    scaleMin: 4.5,
    scaleMax: 7.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-4",
    url: "/scenery-assets/simplenature/Tree4.glb",
    role: "pine_tree",
    weight: 16,
    scaleMin: 4.5,
    scaleMax: 7.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  {
    id: "simple-bush-1",
    url: "/scenery-assets/simplenature/Bush1.glb",
    role: "bush",
    weight: 10,
    scaleMin: 2.2,
    scaleMax: 3.8,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-2",
    url: "/scenery-assets/simplenature/Bush2.glb",
    role: "bush",
    weight: 10,
    scaleMin: 2.2,
    scaleMax: 3.8,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-3",
    url: "/scenery-assets/simplenature/Bush3.glb",
    role: "bush",
    weight: 8,
    scaleMin: 2.0,
    scaleMax: 3.4,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.65,
  },
  {
    id: "simple-grass-1",
    url: "/scenery-assets/simplenature/Grass1.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-2",
    url: "/scenery-assets/simplenature/Grass2.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-3",
    url: "/scenery-assets/simplenature/Grass3.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-rock-1",
    url: "/scenery-assets/simplenature/Rock1.glb",
    role: "rock",
    weight: 6,
    scaleMin: 2.5,
    scaleMax: 4.5,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-2",
    url: "/scenery-assets/simplenature/Rock2.glb",
    role: "rock",
    weight: 6,
    scaleMin: 2.5,
    scaleMax: 4.5,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-3",
    url: "/scenery-assets/simplenature/Rock3.glb",
    role: "rock",
    weight: 4,
    scaleMin: 3.0,
    scaleMax: 5.0,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.9,
  },
  {
    id: "pine-trees",
    url: "/scenery-assets/pine-trees.glb",
    role: "pine_tree",
    weight: 22,
    scaleMin: 22.0,
    scaleMax: 35.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 9.5,
    collisionRadius: 1.4,
  },
  {
    id: "pine-trees-alt",
    url: "/scenery-assets/pine-trees-alt.glb",
    role: "pine_tree",
    weight: 18,
    scaleMin: 3.0,
    scaleMax: 4.8,
    collisionHint: "trunk_canopy",
    collisionHeight: 10.5,
    collisionRadius: 1.4,
  },
  {
    id: "birch-trees",
    url: "/scenery-assets/birch-trees.glb",
    role: "canopy_tree",
    weight: 14,
    scaleMin: 1.8,
    scaleMax: 2.8,
    collisionHint: "trunk_canopy",
    collisionHeight: 8.5,
    collisionRadius: 1.8,
  },
  {
    id: "maple-trees",
    url: "/scenery-assets/maple-trees.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 1.8,
    scaleMax: 2.6,
    collisionHint: "trunk_canopy",
    collisionHeight: 7.5,
    collisionRadius: 1.9,
  },
  {
    id: "bushes",
    url: "/scenery-assets/bushes.glb",
    role: "bush",
    weight: 7,
    scaleMin: 3.0,
    scaleMax: 5.4,
    collisionHint: "sphere",
    collisionHeight: 1.4,
    collisionRadius: 1.0,
  },
  {
    id: "flower-bushes",
    url: "/scenery-assets/flower-bushes.glb",
    role: "bush",
    weight: 5,
    scaleMin: 3.6,
    scaleMax: 6.0,
    collisionHint: "sphere",
    collisionHeight: 1.1,
    collisionRadius: 0.9,
  },
  {
    id: "grass",
    url: "/scenery-assets/grass.glb",
    role: "grass",
    weight: 3,
    scaleMin: 2.7,
    scaleMax: 4.8,
    collisionHint: "none",
    collisionHeight: 0.6,
    collisionRadius: 0,
  },
  {
    id: "rock",
    url: "/scenery-assets/rock.glb",
    role: "rock",
    weight: 5,
    scaleMin: 3.2,
    scaleMax: 6.8,
    collisionHint: "sphere",
    collisionHeight: 1.2,
    collisionRadius: 0.9,
  },
  {
    id: "rock-large",
    url: "/scenery-assets/rock-large.glb",
    role: "rock",
    weight: 3,
    scaleMin: 1.0,
    scaleMax: 1.8,
    collisionHint: "sphere",
    collisionHeight: 2.1,
    collisionRadius: 1.5,
  },
];

export const ACTIVE_SCENERY_ASSET_IDS = [
  "simple-tree-1",
  "simple-tree-2",
  "simple-tree-3",
  "simple-tree-4",
  "simple-bush-1",
  "simple-bush-2",
  "simple-bush-3",
  "simple-grass-1",
  "simple-grass-2",
  "simple-grass-3",
  "simple-rock-1",
  "simple-rock-2",
  "simple-rock-3",
] as const;

export const STARTER_WOODLAND_SCENERY = ACTIVE_SCENERY_ASSET_IDS.map((assetId) => {
  const asset = SCENERY_ASSET_LIBRARY.find((candidate) => candidate.id === assetId);
  if (!asset) {
    throw new Error(`Unknown active scenery asset: ${assetId}`);
  }
  return asset;
});
