// Scale values verified from GLB database (accessor min/max).
// Split trees are tiny after Blender export — need large scale factors.
// User will visually verify and flag any that look wrong.

export type SceneryRole =
  | "pine_tree"
  | "canopy_tree"
  | "bush"
  | "grass"
  | "rock";

export type SceneryCollisionHint = "trunk_canopy" | "sphere" | "none";

export interface SceneryAssetDefinition {
  id: string;
  url: string;
  role: SceneryRole;
  weight: number;
  scaleMin: number;
  scaleMax: number;
  collisionHint: SceneryCollisionHint;
  collisionHeight: number;
  collisionRadius: number;
}

const SCENERY_ASSET_LIBRARY: SceneryAssetDefinition[] = [
  // ======== SimpleNature (heights verified from GLB DB) ========
  // Tree1: 2.41m native → scale 1.2-1.7x for ~3-4m target
  {
    id: "simple-tree-1",
    url: "/scenery-assets/simplenature/Tree1.glb",
    role: "canopy_tree",
    weight: 20,
    scaleMin: 9.6,
    scaleMax: 13.6,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  // Tree2: 1.70m native → scale 1.7-2.4x
  {
    id: "simple-tree-2",
    url: "/scenery-assets/simplenature/Tree2.glb",
    role: "canopy_tree",
    weight: 18,
    scaleMin: 13.6,
    scaleMax: 19.2,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  // Tree3: 2.21m native → scale 1.3-1.8x (pine silhouette)
  {
    id: "simple-tree-3",
    url: "/scenery-assets/simplenature/Tree3.glb",
    role: "pine_tree",
    weight: 18,
    scaleMin: 10.4,
    scaleMax: 14.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  // Tree4: 5.57m native → scale 0.5-0.8x (too big, shrink)
  {
    id: "simple-tree-4",
    url: "/scenery-assets/simplenature/Tree4.glb",
    role: "pine_tree",
    weight: 16,
    scaleMin: 4.0,
    scaleMax: 6.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  // ======== SimpleNature bushes (heights: 0.59-0.99m → scale to ~1.5m) ========
  {
    id: "simple-bush-1",
    url: "/scenery-assets/simplenature/Bush1.glb",
    role: "bush",
    weight: 10,
    scaleMin: 22.4,
    scaleMax: 28.0,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-2",
    url: "/scenery-assets/simplenature/Bush2.glb",
    role: "bush",
    weight: 10,
    scaleMin: 18.0,
    scaleMax: 22.0,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-3",
    url: "/scenery-assets/simplenature/Bush3.glb",
    role: "bush",
    weight: 8,
    scaleMin: 14.0,
    scaleMax: 18.0,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.65,
  },
  // ======== SimpleNature grass (heights: 0.21-0.33m → scale to ~1m) ========
  {
    id: "simple-grass-1",
    url: "/scenery-assets/simplenature/Grass1.glb",
    role: "grass",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-2",
    url: "/scenery-assets/simplenature/Grass2.glb",
    role: "grass",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-3",
    url: "/scenery-assets/simplenature/Grass3.glb",
    role: "grass",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 8.0,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  // ======== SimpleNature rocks (heights: 1.07-2.09m → scale to ~2m) ========
  {
    id: "simple-rock-1",
    url: "/scenery-assets/simplenature/Rock1.glb",
    role: "rock",
    weight: 6,
    scaleMin: 7.2,
    scaleMax: 10.0,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-2",
    url: "/scenery-assets/simplenature/Rock2.glb",
    role: "rock",
    weight: 6,
    scaleMin: 10.0,
    scaleMax: 14.0,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-3",
    url: "/scenery-assets/simplenature/Rock3.glb",
    role: "rock",
    weight: 4,
    scaleMin: 4.8,
    scaleMax: 7.2,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.9,
  },
  // ======== Split single trees (tiny after Blender export — large scale) ========
  // Birch: ~0.01-0.03m native, target ~3.5m → ~100-150x
  {
    id: "birch-1",
    url: "/scenery-assets/BirchTree_1.glb",
    role: "canopy_tree",
    weight: 12,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  {
    id: "birch-2",
    url: "/scenery-assets/BirchTree_2.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  {
    id: "birch-3",
    url: "/scenery-assets/BirchTree_3.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  // Pine: ~0.01m native, target ~4.5m → ~120-195x
  {
    id: "pine-1",
    url: "/scenery-assets/PineTree_1.glb",
    role: "pine_tree",
    weight: 12,
    scaleMin: 8.0,
    scaleMax: 16.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.1,
    collisionRadius: 1.1,
  },
  {
    id: "pine-2",
    url: "/scenery-assets/PineTree_2.glb",
    role: "pine_tree",
    weight: 10,
    scaleMin: 8.0,
    scaleMax: 16.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.1,
    collisionRadius: 1.1,
  },
  {
    id: "pine-3",
    url: "/scenery-assets/PineTree_3.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 16.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.1,
    collisionRadius: 1.1,
  },
  // Maple: ~0.03-0.06m native, target ~3m → ~80-130x
  {
    id: "maple-1",
    url: "/scenery-assets/MapleTree_1.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "maple-2",
    url: "/scenery-assets/MapleTree_2.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "maple-3",
    url: "/scenery-assets/MapleTree_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  // Dead: ~0.01-0.04m native, target ~3m → ~80-130x
  {
    id: "dead-1",
    url: "/scenery-assets/DeadTree_1.glb",
    role: "canopy_tree",
    weight: 5,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-2",
    url: "/scenery-assets/DeadTree_2.glb",
    role: "canopy_tree",
    weight: 4,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-3",
    url: "/scenery-assets/DeadTree_3.glb",
    role: "canopy_tree",
    weight: 3,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  // Normal: ~0.01-0.04m native, target ~3.5m → ~90-150x
  {
    id: "normal-1",
    url: "/scenery-assets/NormalTree_1.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  {
    id: "normal-2",
    url: "/scenery-assets/NormalTree_2.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  {
    id: "normal-3",
    url: "/scenery-assets/NormalTree_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.4,
    collisionRadius: 0.9,
  },
  // Palm: ~0.00-0.02m native, target ~4m → ~105-175x
  {
    id: "palm-1",
    url: "/scenery-assets/PalmTree_1.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 1.0,
  },
  {
    id: "palm-2",
    url: "/scenery-assets/PalmTree_2.glb",
    role: "pine_tree",
    weight: 4,
    scaleMin: 8.0,
    scaleMax: 12.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 1.0,
  },
  // SmallTree: 2.78m native → scale 1.0-1.5x (only split tree at reasonable scale)
  {
    id: "small-1",
    url: "/scenery-assets/SmallTree_01.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 4.0,
    scaleMax: 6.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 1.5,
    collisionRadius: 0.5,
  },
  {
    id: "small-2",
    url: "/scenery-assets/SmallTree_02.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 4.0,
    scaleMax: 6.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 1.5,
    collisionRadius: 0.5,
  },

  // --- New Polypizza individual trees ---
  {
    id: "twisted-1",
    url: "/scenery-assets/Twisted_Tree_8oraKn9m0x.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.15,
    scaleMax: 0.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-2",
    url: "/scenery-assets/Twisted_Tree_9aWlx82xUf.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.15,
    scaleMax: 0.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-3",
    url: "/scenery-assets/Twisted_Tree_edSPJNECM7.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.15,
    scaleMax: 0.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "queen-palm",
    url: "/scenery-assets/Queen_Palm_Tree_ficLBIjGliK.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 0.15,
    scaleMax: 0.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-uxsb",
    url: "/scenery-assets/Tree_uxSb2WTPU4.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.15,
    scaleMax: 0.3,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-qvo",
    url: "/scenery-assets/Tree_QVOop92WmG.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.25,
    scaleMax: 0.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-ywj",
    url: "/scenery-assets/Tree_YWjGDJ9F7g.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.25,
    scaleMax: 0.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-avox",
    url: "/scenery-assets/Tree_aVOxaHRPWe.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.3,
    scaleMax: 0.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-79g",
    url: "/scenery-assets/Pine_79gmlLnweB.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 0.2,
    scaleMax: 0.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-igsu",
    url: "/scenery-assets/Pine_igSu0cPoBz.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 0.25,
    scaleMax: 0.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-699",
    url: "/scenery-assets/Pine_699sFuLCN2.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 0.3,
    scaleMax: 0.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-zt62",
    url: "/scenery-assets/Pine_Zt62gceKXZ.glb",
    role: "pine_tree",
    weight: 8,
    scaleMin: 0.3,
    scaleMax: 0.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-cd4e",
    url: "/scenery-assets/Dead_Tree_CD4edbPSGm.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.12,
    scaleMax: 0.22,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-mlmk",
    url: "/scenery-assets/Dead_Tree_MlmK5488ou.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 0.2,
    scaleMax: 0.38,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },

  // --- Trees from all sources (DB-verified scales) ---
  {
    id: "tree-uxsb2wtpu4",
    url: "/scenery-assets/Tree_uxSb2WTPU4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.15,
    scaleMax: 0.28,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "campfire-0vzzmm-t8cp",
    url: "/scenery-assets/Campfire_0vzzmM-t8CP.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.79,
    scaleMax: 1.46,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-igsu0cpobz",
    url: "/scenery-assets/Pine_igSu0cPoBz.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.25,
    scaleMax: 0.46,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-qztx0ahhcy",
    url: "/scenery-assets/Tree_qZtx0AHhcy.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.31,
    scaleMax: 0.58,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-ywjgdj9f7g",
    url: "/scenery-assets/Tree_YWjGDJ9F7g.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.26,
    scaleMax: 0.48,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-tree-cd4edbpsgm",
    url: "/scenery-assets/Dead_Tree_CD4edbPSGm.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.13,
    scaleMax: 0.24,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-79gmllnweb",
    url: "/scenery-assets/Pine_79gmlLnweB.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.21,
    scaleMax: 0.39,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-zt62gcekxz",
    url: "/scenery-assets/Pine_Zt62gceKXZ.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.3,
    scaleMax: 0.55,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-tree-8orakn9m0x",
    url: "/scenery-assets/Twisted_Tree_8oraKn9m0x.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.14,
    scaleMax: 0.26,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-tree-mcd2zyqyww",
    url: "/scenery-assets/Dead_Tree_Mcd2zYqyww.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.18,
    scaleMax: 0.34,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-699sfulcn2",
    url: "/scenery-assets/Pine_699sFuLCN2.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.29,
    scaleMax: 0.54,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "campfire-dxxhpvxhlzg",
    url: "/scenery-assets/Campfire_dxxHpVXHLZg.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.65,
    scaleMax: 1.21,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-tree-7pdbpelkqr",
    url: "/scenery-assets/Twisted_Tree_7PDBpElkQr.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.12,
    scaleMax: 0.22,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-tree-mlmk5488ou",
    url: "/scenery-assets/Dead_Tree_MlmK5488ou.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.22,
    scaleMax: 0.41,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "queen-palm-tree-ficlbijglik",
    url: "/scenery-assets/Queen_Palm_Tree_ficLBIjGliK.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.15,
    scaleMax: 0.28,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-fall-large-mulevja0gd",
    url: "/scenery-assets/Tree_Fall_Large_mUleVjA0gd.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 2.79,
    scaleMax: 5.18,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-6yjt8niwlsd",
    url: "/scenery-assets/Tree_6Yjt8nIwLsD.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 2.67,
    scaleMax: 4.96,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-tree-gvtsmmuzv7",
    url: "/scenery-assets/Twisted_Tree_GVTsMmuzv7.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.12,
    scaleMax: 0.22,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-t9kbsfydxz",
    url: "/scenery-assets/Tree_t9KbsfYdXz.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.37,
    scaleMax: 0.68,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-rfnxjv0rqa",
    url: "/scenery-assets/Pine_rfnxJv0Rqa.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.3,
    scaleMax: 0.55,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-tree-n8fhmgmldd",
    url: "/scenery-assets/Dead_Tree_n8FhMgMldD.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.16,
    scaleMax: 0.31,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "big-tree-dnwh762pn-6",
    url: "/scenery-assets/Big_Tree_dNWh762PN-6.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.94,
    scaleMax: 1.74,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-2-cripmfhcevu",
    url: "/scenery-assets/Tree-2_cRipmFHCEVU.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.97,
    scaleMax: 1.8,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "dead-tree-om95bd8buf",
    url: "/scenery-assets/Dead_Tree_oM95bD8buf.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.16,
    scaleMax: 0.29,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-tree-9awlx82xuf",
    url: "/scenery-assets/Twisted_Tree_9aWlx82xUf.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.14,
    scaleMax: 0.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-dprqdp0c0y",
    url: "/scenery-assets/Tree_DprqDP0C0y.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 9.09,
    scaleMax: 16.88,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-prskb0kpkk",
    url: "/scenery-assets/Tree_prskB0KPkK.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.74,
    scaleMax: 3.23,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-qvoop92wmg",
    url: "/scenery-assets/Tree_QVOop92WmG.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.26,
    scaleMax: 0.47,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-avoxahrpwe",
    url: "/scenery-assets/Tree_aVOxaHRPWe.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.3,
    scaleMax: 0.56,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree-large-orcbg8dsls",
    url: "/scenery-assets/Tree_Large_ORCbG8dslS.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 2.79,
    scaleMax: 5.18,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "twisted-tree-edspjnecm7",
    url: "/scenery-assets/Twisted_Tree_edSPJNECM7.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.14,
    scaleMax: 0.27,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pine-tree-2qo-fmvkusg",
    url: "/scenery-assets/Pine_Tree_2Qo-fmVKuSG.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 1.06,
    scaleMax: 1.97,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "large-building-ppwtreejxg",
    url: "/scenery-assets/Large_Building_ppwtREejXg.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.25,
    scaleMax: 2.32,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree4",
    url: "/scenery-assets/Tree4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.38,
    scaleMax: 0.7,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree3",
    url: "/scenery-assets/Tree3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.95,
    scaleMax: 1.76,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree2",
    url: "/scenery-assets/Tree2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.23,
    scaleMax: 2.29,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "tree1",
    url: "/scenery-assets/Tree1.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.87,
    scaleMax: 1.62,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-snow-4",
    url: "/scenery-assets/BirchTree_Snow_4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.78,
    scaleMax: 1.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "palmtree-3",
    url: "/scenery-assets/PalmTree_3.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.58,
    scaleMax: 1.08,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "treestump-snow",
    url: "/scenery-assets/TreeStump_Snow.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 3.38,
    scaleMax: 6.27,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pinetree-1",
    url: "/scenery-assets/PineTree_1.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.84,
    scaleMax: 1.57,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "palmtree-2",
    url: "/scenery-assets/PalmTree_2.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.81,
    scaleMax: 1.51,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-snow-5",
    url: "/scenery-assets/BirchTree_Snow_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.48,
    scaleMax: 0.89,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-dead-5",
    url: "/scenery-assets/BirchTree_Dead_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.48,
    scaleMax: 0.89,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pinetree-3",
    url: "/scenery-assets/PineTree_3.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.68,
    scaleMax: 1.26,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pinetree-2",
    url: "/scenery-assets/PineTree_2.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.67,
    scaleMax: 1.24,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-dead-4",
    url: "/scenery-assets/BirchTree_Dead_4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.78,
    scaleMax: 1.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "palmtree-1",
    url: "/scenery-assets/PalmTree_1.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.59,
    scaleMax: 1.09,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-snow-2",
    url: "/scenery-assets/BirchTree_Snow_2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.8,
    scaleMax: 1.48,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-dead-1",
    url: "/scenery-assets/BirchTree_Dead_1.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.93,
    scaleMax: 1.73,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "palmtree-4",
    url: "/scenery-assets/PalmTree_4.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.65,
    scaleMax: 1.21,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-snow-3",
    url: "/scenery-assets/BirchTree_Snow_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.66,
    scaleMax: 1.23,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-snow-1",
    url: "/scenery-assets/BirchTree_Snow_1.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.78,
    scaleMax: 1.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-dead-3",
    url: "/scenery-assets/BirchTree_Dead_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.66,
    scaleMax: 1.23,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pinetree-5",
    url: "/scenery-assets/PineTree_5.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.85,
    scaleMax: 1.57,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "pinetree-4",
    url: "/scenery-assets/PineTree_4.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 0.68,
    scaleMax: 1.25,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "birchtree-dead-2",
    url: "/scenery-assets/BirchTree_Dead_2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.8,
    scaleMax: 1.48,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "commontree-dead-4",
    url: "/scenery-assets/CommonTree_Dead_4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.89,
    scaleMax: 1.65,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-dead-snow-3",
    url: "/scenery-assets/Willow_Dead_Snow_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.1,
    scaleMax: 2.05,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-5",
    url: "/scenery-assets/Willow_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.03,
    scaleMax: 1.92,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-4",
    url: "/scenery-assets/Willow_4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.77,
    scaleMax: 1.43,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-dead-snow-2",
    url: "/scenery-assets/Willow_Dead_Snow_2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.74,
    scaleMax: 1.38,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "commontree-dead-5",
    url: "/scenery-assets/CommonTree_Dead_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.91,
    scaleMax: 1.7,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "commontree-snow-5",
    url: "/scenery-assets/CommonTree_Snow_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.91,
    scaleMax: 1.7,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "commontree-snow-4",
    url: "/scenery-assets/CommonTree_Snow_4.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.89,
    scaleMax: 1.65,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-dead-snow-1",
    url: "/scenery-assets/Willow_Dead_Snow_1.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.78,
    scaleMax: 1.45,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "commontree-dead-2",
    url: "/scenery-assets/CommonTree_Dead_2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.71,
    scaleMax: 1.32,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-dead-snow-5",
    url: "/scenery-assets/Willow_Dead_Snow_5.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.03,
    scaleMax: 1.92,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-3",
    url: "/scenery-assets/Willow_3.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.1,
    scaleMax: 2.05,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
  {
    id: "willow-2",
    url: "/scenery-assets/Willow_2.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 0.74,
    scaleMax: 1.38,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.1,
    collisionRadius: 0.8,
  },
];

export const ACTIVE_SCENERY_ASSET_IDS = [
  "simple-tree-1", "simple-tree-2", "simple-tree-3", "simple-tree-4",
  "small-1", "small-2",
  "simple-bush-1", "simple-bush-2", "simple-bush-3",
  "simple-grass-1", "simple-grass-2", "simple-grass-3",
  "simple-rock-1", "simple-rock-2", "simple-rock-3",
  "birch-1", "birch-2", "birch-3",
  "pine-1", "pine-2", "pine-3",
  "maple-1", "maple-2", "maple-3",
  "dead-1", "dead-2", "dead-3",
  "normal-1", "normal-2", "normal-3",
  "palm-1", "palm-2",
,
  "twisted-1",
  "twisted-2",
  "twisted-3",
  "queen-palm",
  "tree-uxsb",
  "tree-qvo",
  "tree-ywj",
  "tree-avox",
  "pine-79g",
  "pine-igsu",
  "pine-699",
  "pine-zt62",
  "dead-cd4e",
  "dead-mlmk",
  "tree-uxsb2wtpu4",
  "campfire-0vzzmm-t8cp",
  "pine-igsu0cpobz",
  "tree-qztx0ahhcy",
  "tree-ywjgdj9f7g",
  "dead-tree-cd4edbpsgm",
  "pine-79gmllnweb",
  "pine-zt62gcekxz",
  "twisted-tree-8orakn9m0x",
  "dead-tree-mcd2zyqyww",
  "pine-699sfulcn2",
  "campfire-dxxhpvxhlzg",
  "twisted-tree-7pdbpelkqr",
  "dead-tree-mlmk5488ou",
  "queen-palm-tree-ficlbijglik",
  "tree-fall-large-mulevja0gd",
  "tree-6yjt8niwlsd",
  "twisted-tree-gvtsmmuzv7",
  "tree-t9kbsfydxz",
  "pine-rfnxjv0rqa",
  "dead-tree-n8fhmgmldd",
  "big-tree-dnwh762pn-6",
  "tree-2-cripmfhcevu",
  "dead-tree-om95bd8buf",
  "twisted-tree-9awlx82xuf",
  "tree-dprqdp0c0y",
  "tree-prskb0kpkk",
  "tree-qvoop92wmg",
  "tree-avoxahrpwe",
  "tree-large-orcbg8dsls",
  "twisted-tree-edspjnecm7",
  "pine-tree-2qo-fmvkusg",
  "large-building-ppwtreejxg",
  "tree4",
  "tree3",
  "tree2",
  "tree1",
  "birchtree-snow-4",
  "palmtree-3",
  "treestump-snow",
  "pinetree-1",
  "palmtree-2",
  "birchtree-snow-5",
  "birchtree-dead-5",
  "pinetree-3",
  "pinetree-2",
  "birchtree-dead-4",
  "palmtree-1",
  "birchtree-snow-2",
  "birchtree-dead-1",
  "palmtree-4",
  "birchtree-snow-3",
  "birchtree-snow-1",
  "birchtree-dead-3",
  "pinetree-5",
  "pinetree-4",
  "birchtree-dead-2",
  "commontree-dead-4",
  "willow-dead-snow-3",
  "willow-5",
  "willow-4",
  "willow-dead-snow-2",
  "commontree-dead-5",
  "commontree-snow-5",
  "commontree-snow-4",
  "willow-dead-snow-1",
  "commontree-dead-2",
  "willow-dead-snow-5",
  "willow-3",
  "willow-2"] as const;

export const STARTER_WOODLAND_SCENERY = ACTIVE_SCENERY_ASSET_IDS.map((assetId) => {
  const asset = SCENERY_ASSET_LIBRARY.find((candidate) => candidate.id === assetId);
  if (!asset) {
    throw new Error(`Unknown active scenery asset: ${assetId}`);
  }
  return asset;
});
