export type SceneryRole =
  | "pine_tree"
  | "canopy_tree"
  | "bush"
  | "grass"
  | "rock";

export type SceneryCollisionHint = "trunk_canopy" | "sphere" | "none";

export interface SceneryAssetDefinition {
  id: string;
  url: string;
  role: SceneryRole;
  weight: number;
  scaleMin: number;
  scaleMax: number;
  collisionHint: SceneryCollisionHint;
  collisionHeight: number;
  collisionRadius: number;
}

const SCENERY_ASSET_LIBRARY: SceneryAssetDefinition[] = [
  {
    id: "simple-tree-1",
    url: "/scenery-assets/simplenature/Tree1.glb",
    role: "canopy_tree",
    weight: 20,
    scaleMin: 4.5,
    scaleMax: 7.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-2",
    url: "/scenery-assets/simplenature/Tree2.glb",
    role: "canopy_tree",
    weight: 18,
    scaleMin: 4.5,
    scaleMax: 7.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 2.8,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-3",
    url: "/scenery-assets/simplenature/Tree3.glb",
    role: "pine_tree",
    weight: 18,
    scaleMin: 4.5,
    scaleMax: 7.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  {
    id: "simple-tree-4",
    url: "/scenery-assets/simplenature/Tree4.glb",
    role: "pine_tree",
    weight: 16,
    scaleMin: 4.5,
    scaleMax: 7.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.0,
    collisionRadius: 0.9,
  },
  {
    id: "simple-bush-1",
    url: "/scenery-assets/simplenature/Bush1.glb",
    role: "bush",
    weight: 10,
    scaleMin: 2.2,
    scaleMax: 3.8,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-2",
    url: "/scenery-assets/simplenature/Bush2.glb",
    role: "bush",
    weight: 10,
    scaleMin: 2.2,
    scaleMax: 3.8,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.7,
  },
  {
    id: "simple-bush-3",
    url: "/scenery-assets/simplenature/Bush3.glb",
    role: "bush",
    weight: 8,
    scaleMin: 2.0,
    scaleMax: 3.4,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.65,
  },
  {
    id: "simple-grass-1",
    url: "/scenery-assets/simplenature/Grass1.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-2",
    url: "/scenery-assets/simplenature/Grass2.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-grass-3",
    url: "/scenery-assets/simplenature/Grass3.glb",
    role: "grass",
    weight: 8,
    scaleMin: 2.4,
    scaleMax: 4.2,
    collisionHint: "none",
    collisionHeight: 0.5,
    collisionRadius: 0,
  },
  {
    id: "simple-rock-1",
    url: "/scenery-assets/simplenature/Rock1.glb",
    role: "rock",
    weight: 6,
    scaleMin: 2.5,
    scaleMax: 4.5,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-2",
    url: "/scenery-assets/simplenature/Rock2.glb",
    role: "rock",
    weight: 6,
    scaleMin: 2.5,
    scaleMax: 4.5,
    collisionHint: "sphere",
    collisionHeight: 0.7,
    collisionRadius: 0.8,
  },
  {
    id: "simple-rock-3",
    url: "/scenery-assets/simplenature/Rock3.glb",
    role: "rock",
    weight: 4,
    scaleMin: 3.0,
    scaleMax: 5.0,
    collisionHint: "sphere",
    collisionHeight: 0.8,
    collisionRadius: 0.9,
  },
  // --- Single trees (from split clusters) ---
  {
    id: "birch-1",
    url: "/scenery-assets/BirchTree_1.glb",
    role: "canopy_tree",
    weight: 16,
    scaleMin: 1.4,
    scaleMax: 2.2,
    collisionHint: "trunk_canopy",
    collisionHeight: 7.0,
    collisionRadius: 1.6,
  },
  {
    id: "birch-2",
    url: "/scenery-assets/BirchTree_2.glb",
    role: "canopy_tree",
    weight: 14,
    scaleMin: 1.4,
    scaleMax: 2.2,
    collisionHint: "trunk_canopy",
    collisionHeight: 7.0,
    collisionRadius: 1.6,
  },
  {
    id: "birch-3",
    url: "/scenery-assets/BirchTree_3.glb",
    role: "canopy_tree",
    weight: 12,
    scaleMin: 1.4,
    scaleMax: 2.2,
    collisionHint: "trunk_canopy",
    collisionHeight: 7.0,
    collisionRadius: 1.6,
  },
  {
    id: "pine-1",
    url: "/scenery-assets/PineTree_1.glb",
    role: "pine_tree",
    weight: 16,
    scaleMin: 1.4,
    scaleMax: 2.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 9.0,
    collisionRadius: 1.3,
  },
  {
    id: "pine-2",
    url: "/scenery-assets/PineTree_2.glb",
    role: "pine_tree",
    weight: 14,
    scaleMin: 1.4,
    scaleMax: 2.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 9.0,
    collisionRadius: 1.3,
  },
  {
    id: "pine-3",
    url: "/scenery-assets/PineTree_3.glb",
    role: "pine_tree",
    weight: 12,
    scaleMin: 1.4,
    scaleMax: 2.4,
    collisionHint: "trunk_canopy",
    collisionHeight: 9.0,
    collisionRadius: 1.3,
  },
  {
    id: "maple-1",
    url: "/scenery-assets/MapleTree_1.glb",
    role: "canopy_tree",
    weight: 12,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.5,
    collisionRadius: 1.7,
  },
  {
    id: "maple-2",
    url: "/scenery-assets/MapleTree_2.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.5,
    collisionRadius: 1.7,
  },
  {
    id: "maple-3",
    url: "/scenery-assets/MapleTree_3.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.5,
    collisionRadius: 1.7,
  },
  {
    id: "dead-1",
    url: "/scenery-assets/DeadTree_1.glb",
    role: "canopy_tree",
    weight: 5,
    scaleMin: 1.4,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.0,
    collisionRadius: 1.2,
  },
  {
    id: "dead-2",
    url: "/scenery-assets/DeadTree_2.glb",
    role: "canopy_tree",
    weight: 4,
    scaleMin: 1.4,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.0,
    collisionRadius: 1.2,
  },
  {
    id: "dead-3",
    url: "/scenery-assets/DeadTree_3.glb",
    role: "canopy_tree",
    weight: 3,
    scaleMin: 1.4,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 6.0,
    collisionRadius: 1.2,
  },
  {
    id: "normal-1",
    url: "/scenery-assets/NormalTree_1.glb",
    role: "canopy_tree",
    weight: 14,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 5.5,
    collisionRadius: 1.4,
  },
  {
    id: "normal-2",
    url: "/scenery-assets/NormalTree_2.glb",
    role: "canopy_tree",
    weight: 12,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 5.5,
    collisionRadius: 1.4,
  },
  {
    id: "normal-3",
    url: "/scenery-assets/NormalTree_3.glb",
    role: "canopy_tree",
    weight: 10,
    scaleMin: 1.3,
    scaleMax: 2.0,
    collisionHint: "trunk_canopy",
    collisionHeight: 5.5,
    collisionRadius: 1.4,
  },
  {
    id: "palm-1",
    url: "/scenery-assets/PalmTree_1.glb",
    role: "pine_tree",
    weight: 6,
    scaleMin: 1.2,
    scaleMax: 1.8,
    collisionHint: "trunk_canopy",
    collisionHeight: 5.0,
    collisionRadius: 1.0,
  },
  {
    id: "palm-2",
    url: "/scenery-assets/PalmTree_2.glb",
    role: "pine_tree",
    weight: 4,
    scaleMin: 1.2,
    scaleMax: 1.8,
    collisionHint: "trunk_canopy",
    collisionHeight: 5.0,
    collisionRadius: 1.0,
  },
  {
    id: "small-1",
    url: "/scenery-assets/SmallTree_01.glb",
    role: "canopy_tree",
    weight: 8,
    scaleMin: 1.5,
    scaleMax: 2.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.5,
    collisionRadius: 1.0,
  },
  {
    id: "small-2",
    url: "/scenery-assets/SmallTree_02.glb",
    role: "canopy_tree",
    weight: 6,
    scaleMin: 1.5,
    scaleMax: 2.5,
    collisionHint: "trunk_canopy",
    collisionHeight: 3.5,
    collisionRadius: 1.0,
  },
];

export const ACTIVE_SCENERY_ASSET_IDS = [
  "simple-tree-1",
  "simple-tree-2",
  "simple-tree-3",
  "simple-tree-4",
  "simple-bush-1",
  "simple-bush-2",
  "simple-bush-3",
  "simple-grass-1",
  "simple-grass-2",
  "simple-grass-3",
  "simple-rock-1",
  "simple-rock-2",
  "simple-rock-3",
  "birch-1",
  "birch-2",
  "birch-3",
  "pine-1",
  "pine-2",
  "pine-3",
  "maple-1",
  "maple-2",
  "maple-3",
  "dead-1",
  "dead-2",
  "dead-3",
  "normal-1",
  "normal-2",
  "normal-3",
  "palm-1",
  "palm-2",
  "small-1",
  "small-2",
] as const;

export const STARTER_WOODLAND_SCENERY = ACTIVE_SCENERY_ASSET_IDS.map((assetId) => {
  const asset = SCENERY_ASSET_LIBRARY.find((candidate) => candidate.id === assetId);
  if (!asset) {
    throw new Error(`Unknown active scenery asset: ${assetId}`);
  }
  return asset;
});
